// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd4hXsNvhu4YsfZWDSdsy0lZRfpPw0YIY',
    appId: '1:9248017139:web:bc49869e074c55bbad8586',
    messagingSenderId: '9248017139',
    projectId: 'codexa-api',
    authDomain: 'codexa-api.firebaseapp.com',
    storageBucket: 'codexa-api.firebasestorage.app',
    measurementId: 'G-E5KYDYBKQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBTv3TIyY6awbgutMldopLXHhnNzWg-Wo',
    appId: '1:9248017139:android:3d19e1cf0457be80ad8586',
    messagingSenderId: '9248017139',
    projectId: 'codexa-api',
    storageBucket: 'codexa-api.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtWmKxSnslRWh8z7dU3R6teDuYxn9BOUs',
    appId: '1:9248017139:ios:725e3ea2d59b2949ad8586',
    messagingSenderId: '9248017139',
    projectId: 'codexa-api',
    storageBucket: 'codexa-api.firebasestorage.app',
    iosClientId: '9248017139-hl1gm8h2jb231dv8fpnsb7mjqlu4n867.apps.googleusercontent.com',
    iosBundleId: 'com.example.codexaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtWmKxSnslRWh8z7dU3R6teDuYxn9BOUs',
    appId: '1:9248017139:ios:725e3ea2d59b2949ad8586',
    messagingSenderId: '9248017139',
    projectId: 'codexa-api',
    storageBucket: 'codexa-api.firebasestorage.app',
    iosClientId: '9248017139-hl1gm8h2jb231dv8fpnsb7mjqlu4n867.apps.googleusercontent.com',
    iosBundleId: 'com.example.codexaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd4hXsNvhu4YsfZWDSdsy0lZRfpPw0YIY',
    appId: '1:9248017139:web:e0320021932aee7aad8586',
    messagingSenderId: '9248017139',
    projectId: 'codexa-api',
    authDomain: 'codexa-api.firebaseapp.com',
    storageBucket: 'codexa-api.firebasestorage.app',
    measurementId: 'G-TDCLXWFQEB',
  );
}
